-- 코드를 입력하세요
SELECT WAREHOUSE_ID , WAREHOUSE_NAME , ADDRESS,
CASE WHEN FREEZER_YN is null THEN 'N'
ELSE FREEZER_YN
end as FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS like '%경기도%'
order by WAREHOUSE_ID asc;