-- SELECT * 
--  FROM (SELECT F.FLAVOR
--     FROM FIRST_HALF F JOIN JULY J ON F.FLAVOR = J.FLAVOR
--     GROUP BY F.FLAVOR          
--     ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
-- )
-- WHERE ROWNUM <= 3;
 
SELECT F.FLAVOR
FROM FIRST_HALF F JOIN JULY J ON F.FLAVOR = J.FLAVOR
group by F.FLAVOR
order by sum(F.TOTAL_ORDER + J.TOTAL_ORDER) desc
FETCH FIRST 3 ROWS ONLY;