-- 코드를 작성해주세요
SELECT sum(HG.SCORE) as SCORE, HG.EMP_NO , HE.EMP_NAME , HE.POSITION , HE.EMAIL
FROM HR_EMPLOYEES HE inner join HR_GRADE HG on HE.EMP_NO = HG.EMP_NO
GROUP BY HE.EMP_NO
order by sum(HG.SCORE) desc
LIMIT 1