SELECT ub.TITLE , ub.BOARD_ID , ur.REPLY_ID , ur.WRITER_ID , ur.CONTENTS, 
date_format(ur.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD ub INNER JOIN USED_GOODS_REPLY ur ON ub.BOARD_ID = ur.BOARD_ID
WHERE date_format(ub.CREATED_DATE , "%Y-%m") = '2022-10'
ORDER BY ur.CREATED_DATE ASC , ub.TITLE ASC