# SELECT B.CATEGORY ,COUNT(*) AS TOTAL_SALES
SELECT B.CATEGORY , SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B INNER join BOOK_SALES BS on B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY
ORDER BY 1 ASC;